// vueWeb/src/modules/mails/list/index.vue
<template>
  <div class="mails-list">
    <router-link v-for="mail in mails" :key="mail.id" :to=mail.id class="mail">
      <Thumbnail :mail=mail />
    </router-link>
  </div>
</template>

<script>
  import Thumbnail from "@/modules/mails/thumbnail";

  export default {
    name: 'MailsList',
    components: { Thumbnail },
    props: {
      mails: Array,
    }
  }
</script>

// reactWeb/src/modules/mails/list/index.tsx
import React from 'react';
import { NavLink } from 'react-router-dom';
import Thumbnail from '../thumbnail';
import Mail from '../model';

export interface Props {
  mails: Mail[];
}

function List({ mails }: Props): React.ReactElement {
  return (
    <div className="mails-list">
      {mails.map((mail: Mail) => (
        <NavLink to={`/${mail.id}`} className="mail" key={mail.id}>
          <Thumbnail mail={mail} />
        </NavLink>
      ))}
    </div>
  );
}

export default List;
