// vueWeb/src/modules/mails/landing/index.vue
<template>
  <div class="mails-landing">
    <div class="list">
      <List :mails="mails" />
    </div>
    <div class="viewer" v-if="selectedMail">
      <Viewer :selectedMail=selectedMail />
    </div>
  </div>
</template>

<script>
  import List from '../list';
  import Viewer from '../viewer';
  import { fetchMails } from "@/modules/mails/api.js";

  export default {
    name: 'MailsLanding',
    components: {
      List,
      Viewer
    },
    data() {
      return {
        mails: [],
        selectedMail: null
      }
    },
    async mounted() {
      this.mails = await fetchMails();

      if (!this.mails.length) {
        await this.$router.push('/');
      } else if ('mail' in this.$route.params && this.$route.params.mail) {
        const currentMail = this.mails.find((mail) => mail.id === this.$route.params.mail);

        if (!currentMail) {
          await this.$router.push(`/${this.mails[0].id}`);
          this.selectedMail = this.mails[0];
        } else {
          this.selectedMail = currentMail;
        }
      } else {
        await this.$router.push(`/${this.mails[0].id}`);
        this.selectedMail = this.mails[0];
      }
    },
    watch: {
      async '$route' (to) {
        console.log("THERE")
        if (!this.mails.length) {
          await this.$router.push('/');
        } else if ('mail' in to.params && to.params.mail) {
          const currentMail = this.mails.find((mail) => mail.id === to.params.mail);

          if (!currentMail) {
            await this.$router.push(`/${this.mails[0].id}`);
            this.selectedMail = this.mails[0];
          } else {
            this.selectedMail = currentMail;
          }
        } else {
          await this.$router.push(`/${this.mails[0].id}`);
          this.selectedMail = this.mails[0];
        }
      }
    }
  }
</script>

// reactWeb/src/modules/mails/landing/index.tsx
import React, { useEffect, useState } from 'react';
import { useParams, useHistory } from 'react-router-dom';
import List from '../list';
import Viewer from '../viewer';
import { useMails } from '../api';
import Mail from '../model';

function Landing(): React.ReactElement {
  const { pending, mails } = useMails();
  const history = useHistory();
  const params = useParams<{ mail?: string }>();
  const [selectedMail, setSelectedMail] = useState<Mail | undefined>();

  useEffect(() => {
    if (pending) {
      // Nothing
    } else if (!mails.length) {
      history.push('/');
    } else if ('mail' in params && params.mail) {
      const currentMail = mails.find((mail: Mail) => mail.id === params.mail);
      if (!currentMail) {
        history.push(`/${mails[0].id}`);
        setSelectedMail(mails[0]);
      } else {
        setSelectedMail(currentMail);
      }
    } else {
      history.push(`/${mails[0].id}`);
      setSelectedMail(mails[0]);
    }
  }, [pending, params.mail, mails]);

  return (
    <div className="mails-landing">
      <div className="list">
        <List mails={mails} />
      </div>
      {selectedMail ? (
        <div className="viewer">
          <Viewer selectedMail={selectedMail} />
        </div>
      ) : null}
    </div>
  );
}

export default Landing;
