// vueWeb/src/modules/mails/viewer/bodyPart.vue
<template>
  <iframe v-if="htmlBody.type === 'text/html'" :srcDoc=bodyValue.value scrolling="no" />
  <p class="textBody" v-else>{{ bodyValue.value }}</p>
</template>

<script>
  export default {
    name: 'MailsViewerBodyPart',
    props: {
      htmlBody: { type: Object, required: true },
      bodyValue: { type: Object, required: true },
    }
  }
</script>

// svelteWeb/src/modules/BodyPart.svelte
<script lang="ts">
  import {BodyValue, HtmlBodyPart} from "./mails/model";

  export let htmlBody: HtmlBodyPart
  export let bodyValue: BodyValue
</script>

{#if htmlBody.type === 'text/html'}
  <iframe srcDoc={bodyValue.value} scrolling="no"></iframe>
{:else }
  <p class="textBody">{ bodyValue.value }</p>
{/if}
