// svelteWeb/src/modules/BodyPart.svelte
<script lang="ts">
  import {BodyValue, HtmlBodyPart} from "./mails/model";

  export let htmlBody: HtmlBodyPart
  export let bodyValue: BodyValue
</script>

{#if htmlBody.type === 'text/html'}
  <iframe srcDoc={bodyValue.value} scrolling="no"></iframe>
{:else }
  <p class="textBody">{ bodyValue.value }</p>
{/if}

// reactWeb/src/modules/mails/viewer/bodyPart.tsx
import React from 'react';
import { BodyValue, HtmlBodyPart, MimeType } from '../model';

export interface Props {
  htmlBody: HtmlBodyPart;
  bodyValue: BodyValue;
}

function BodyPart({ htmlBody, bodyValue }: Props): React.ReactElement {
  switch (htmlBody.type) {
    case MimeType.TEXT_HTML:
      return <iframe srcDoc={bodyValue.value} scrolling="no" />;
    default:
      return <p className='textBody'>{bodyValue.value}</p>;
  }
}

export default BodyPart;
