// reactNative/src/modules/mails/thumbnail/index.tsx
import React from 'react';
import { View, Text } from 'react-native';
import Mail from '../model';
import style from './style';
import { formatRelativeTime } from '../../../helpers/time';

export interface Props {
  mail: Mail;
}

function Thumbnail({ mail }: Props): React.ReactElement {
  return (
    <View style={style.container}>
      <View style={style.body}>
        <Text style={style.from} numberOfLines={1}>
          {mail.from?.name || mail.from?.email}
        </Text>
        <Text style={style.subject} numberOfLines={1}>
          {mail.subject}
        </Text>
      </View>
      <View style={style.metas}>
        {mail.receivedAt ? (
          <Text style={style.receivedAt} numberOfLines={1}>
            {formatRelativeTime(mail.receivedAt)}
          </Text>
        ) : null}
      </View>
    </View>
  );
}

export default Thumbnail;

// vueWeb/src/modules/mails/thumbnail/index.vue
<template>
  <div class="mails-thumbnail">
    <div class="infos">
      <p class="name">{{ mail.from.name }}</p>
      <p class="subject">{{ mail.subject }}</p>
    </div>
    <div class="metas">
      <p>{{ receivedAt }}</p>
    </div>
  </div>
</template>

<script>
  import { formatRelativeTime } from "@/helpers/time";

  export default {
    name: 'MailsThumbnail',
    props: {
      mail: { type: Object, required: true },
    },
    computed: {
      receivedAt: function () {
        return formatRelativeTime(this.mail.receivedAt);
      }
    }
  }
</script>
