// reactWeb/src/modules/mails/thumbnail/index.tsx
import React from 'react';
import Mail from '../model';
import { formatRelativeTime } from '../../../helpers/time';

export interface Props {
  mail: Mail;
}

function Thumbnail({ mail }: Props): React.ReactElement {
  return (
    <div className="mails-thumbnail">
      <div className="infos">
        <p className="name">{mail.from?.name}</p>
        <p className="subject">{mail.subject}</p>
      </div>
      <div className="metas">
        {mail.receivedAt ? <p>{formatRelativeTime(mail.receivedAt)}</p> : null}
      </div>
    </div>
  );
}

export default Thumbnail;

// vueWeb/src/modules/mails/thumbnail/index.vue
<template>
  <div class="mails-thumbnail">
    <div class="infos">
      <p class="name">{{ mail.from.name }}</p>
      <p class="subject">{{ mail.subject }}</p>
    </div>
    <div class="metas">
      <p>{{ receivedAt }}</p>
    </div>
  </div>
</template>

<script>
  import { formatRelativeTime } from "@/helpers/time";

  export default {
    name: 'MailsThumbnail',
    props: {
      mail: { type: Object, required: true },
    },
    computed: {
      receivedAt: function () {
        return formatRelativeTime(this.mail.receivedAt);
      }
    }
  }
</script>
