// reactNative/src/modules/mails/viewer/index.tsx
import React, { useEffect, useState } from 'react';
import {
  View,
  Text,
  SafeAreaView,
  TouchableWithoutFeedback,
  ScrollView,
} from 'react-native';
import { useRoute, RouteProp, useNavigation } from '@react-navigation/native';
import { useMail } from '../api';
import Mail, { HtmlBodyPart } from '../model';
import style from './style';
import ChevronLeft from '../../../theme/icons/chevronLeft';
import { formatRelativeTime } from '../../../helpers/time';
import BodyPart from './bodyPart';

function Viewer(): React.ReactElement {
  const route = useRoute<RouteProp<{ params: { mail: Mail } }, 'params'>>();
  const navigation = useNavigation();
  const [resolvedMail, setResolvedMail] = useState<Mail>(route.params.mail);

  const mail = useMail(route.params.mail.id);

  useEffect(() => {
    if (mail.mail) {
      setResolvedMail(mail.mail);
    }
  }, [mail]);

  return (
    <View style={style.container}>
      <SafeAreaView>
        <View style={style.header}>
          <TouchableWithoutFeedback onPress={navigation.goBack}>
            <View style={style.navigation}>
              <ChevronLeft />
              <View style={style.metas}>
                <Text style={style.name}>{resolvedMail.from?.name}</Text>
                <Text style={style.email}>{resolvedMail.from?.email}</Text>
              </View>
            </View>
          </TouchableWithoutFeedback>

          {resolvedMail.receivedAt ? (
            <Text style={style.time}>
              {formatRelativeTime(resolvedMail.receivedAt)}
            </Text>
          ) : null}
        </View>
      </SafeAreaView>

      <ScrollView contentContainerStyle={style.body}>
        <Text style={style.subject}>{mail.mail?.subject}</Text>

        {resolvedMail.htmlBody && resolvedMail.htmlBody.length
          ? resolvedMail.htmlBody.map((htmlBody: HtmlBodyPart) =>
              resolvedMail.bodyValues &&
              htmlBody.partId in resolvedMail.bodyValues ? (
                <View style={style.bodyPart} key={htmlBody.partId}>
                  <BodyPart
                    htmlBody={htmlBody}
                    bodyValue={resolvedMail.bodyValues[htmlBody.partId]}
                  />
                </View>
              ) : null,
            )
          : null}
      </ScrollView>
    </View>
  );
}

export default Viewer;

// vueWeb/src/modules/mails/viewer/index.vue
<template>
  <div class="mails-viewer">
    <div class="header">
      <div class="infos">
        <p class="name">{{ selectedMail.from.name }}</p>
        <p class="mail">{{ selectedMail.from.email }}</p>
      </div>
      <div class="metas">
        <p class="receivedAt">{{ receivedAt }}</p>
      </div>
    </div>
    <div class="body">
      <h1>{{ selectedMail.subject }}</h1>

      <template v-if="mail.htmlBody">
        <div v-for="htmlBody in mail.htmlBody" :key=htmlBody.partId>
          <BodyPart :htmlBody=htmlBody :bodyValue=mail.bodyValues[htmlBody.partId] />
        </div>
      </template>
    </div>
  </div>
</template>

<script>
  import { formatRelativeTime } from "@/helpers/time";
  import { fetchMail } from "@/modules/mails/api";
  import BodyPart from "./bodyPart";

  export default {
    name: 'MailsViewer',
    components: {
      BodyPart
    },
    props: {
      selectedMail: { type: Object, required: true }
    },
    data() {
      return {
        mail: this.selectedMail
      }
    },
    computed: {
      receivedAt: function () {
        return formatRelativeTime(this.selectedMail.receivedAt);
      }
    },
    async mounted() {
      this.mail = await fetchMail(this.selectedMail.id);
    }
  }
</script>
