// reactWeb/src/modules/mails/viewer/index.tsx
import React, { useEffect, useState } from 'react';
import Mail, { HtmlBodyPart } from '../model';
import { useMail } from '../api';
import { formatRelativeTime } from '../../../helpers/time';
import BodyPart from './bodyPart';

export interface Props {
  selectedMail: Mail;
}

function Viewer({ selectedMail }: Props): React.ReactElement {
  const [mail, setMail] = useState<Mail>(selectedMail);

  const fetchedMail = useMail(selectedMail.id);

  useEffect(() => {
    if (!fetchedMail.pending && fetchedMail.mail) {
      setMail(fetchedMail.mail);
    } else {
      setMail(selectedMail);
    }
  }, [selectedMail, fetchedMail]);

  return (
    <div className="mails-viewer">
      <div className="header">
        <div className="infos">
          <p className="name">{selectedMail.from?.name}</p>
          <p className="mail">{selectedMail.from?.email}</p>
        </div>
        <div className="metas">
          {selectedMail.receivedAt ? (
            <p className="receivedAt">{formatRelativeTime(selectedMail.receivedAt)}</p>
          ) : null}
        </div>
      </div>
      <div className="body">
        <h1>{selectedMail.subject}</h1>

        {mail.htmlBody && mail.htmlBody.length
          ? mail.htmlBody.map((htmlBody: HtmlBodyPart) =>
              mail.bodyValues && htmlBody.partId in mail.bodyValues ? (
                <div key={htmlBody.partId}>
                  <BodyPart htmlBody={htmlBody} bodyValue={mail.bodyValues[htmlBody.partId]} />
                </div>
              ) : null
            )
          : null}
      </div>
    </div>
  );
}

export default Viewer;

// vueWeb/src/modules/mails/viewer/index.vue
<template>
  <div class="mails-viewer">
    <div class="header">
      <div class="infos">
        <p class="name">{{ selectedMail.from.name }}</p>
        <p class="mail">{{ selectedMail.from.email }}</p>
      </div>
      <div class="metas">
        <p class="receivedAt">{{ receivedAt }}</p>
      </div>
    </div>
    <div class="body">
      <h1>{{ selectedMail.subject }}</h1>

      <template v-if="mail.htmlBody">
        <div v-for="htmlBody in mail.htmlBody" :key=htmlBody.partId>
          <BodyPart :htmlBody=htmlBody :bodyValue=mail.bodyValues[htmlBody.partId] />
        </div>
      </template>
    </div>
  </div>
</template>

<script>
  import { formatRelativeTime } from "@/helpers/time";
  import { fetchMail } from "@/modules/mails/api";
  import BodyPart from "./bodyPart";

  export default {
    name: 'MailsViewer',
    components: {
      BodyPart
    },
    props: {
      selectedMail: { type: Object, required: true }
    },
    data() {
      return {
        mail: this.selectedMail
      }
    },
    computed: {
      receivedAt: function () {
        return formatRelativeTime(this.selectedMail.receivedAt);
      }
    },
    async mounted() {
      this.mail = await fetchMail(this.selectedMail.id);
    }
  }
</script>
